In [4]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt

def visualize_o3d(xyz, labels=None, rgb=None, point_size=1.0):
    """
    xyz: torch.Tensor (N,3)
    labels: torch.Tensor (N,)
    rgb: torch.Tensor (N,3) floating 0..1
    """

    xyz = xyz.detach().cpu().numpy()

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(xyz)

    if rgb is not None:
        rgb = rgb.detach().cpu().numpy()
        rgb = rgb.astype(np.float32)
        if rgb.max() > 1.0:
            rgb = rgb / 255.0

        pcd.colors = o3d.utility.Vector3dVector(rgb)


    elif labels is not None:
        labels = labels.detach().cpu().numpy()
        # colormap
        cmap = plt.get_cmap("tab20")
        max_label = max(labels.max(), 1)
        colors = cmap(labels / max_label)[:, :3]
        pcd.colors = o3d.utility.Vector3dVector(colors)

    # Включаем красивое отображение
    vis = o3d.visualization.Visualizer()
    vis.create_window(width=1000, height=800)
    vis.add_geometry(pcd)

    opt = vis.get_render_option()
    opt.point_size = point_size
    opt.background_color = np.asarray([0, 0, 0])

    vis.run()
    vis.destroy_window()

In [5]:
import os
print(os.listdir("/home/pavel/ITMO/NIR2/SensatUrban_train"))
print(os.listdir("/home/pavel/ITMO/NIR2/SensatUrban_train/SensatUrban"))


['RandLaNetTrain', 'SensatUrban', 'temp', '__init__.py', '.project-root', '__pycache__']
['README.md', 'LICENSE', 'helper_ply.py', 'RandLANet.py', 'tool.py', 'tf_util.py', '.git', 'main_SensatUrban.py', 'helper_requirements.txt', '__init__.py', 'input_preparation.py', 'cpp_wrappers', 'compile_op.sh', '.gitignore', 'tester_SensatUrban.py', 'imgs', '__pycache__', 'utils']


In [7]:
from  dataset import SensatUrbanDataset

ROOT = "/home/pavel/ITMO/NIR2/data/SensetUrban_converted"

dataset = SensatUrbanDataset(ROOT, "train", voxel_size=0.2)

xyz, feats, labels = dataset[1]

# feats = [xyz, rgb], поэтому:
rgb = feats[:, 3:6]

# Вариант 1 — посмотреть XYZ + LABELS
# visualize_o3d(xyz, labels=labels)

# Вариант 2 — посмотреть RGB (без labels)
visualize_o3d(xyz, rgb=rgb)


/home/pavel/ITMO/NIR2/data/SensetUrban_converted/train/cambridge_block_19.ply
[ 0  1  2  3  5  7  8  9 10 11]
[[ 32  36  42]
 [ 58  68  76]
 [101  82  43]
 ...
 [ 63  54  32]
 [ 52  66  17]
 [ 50  68  25]]


KeyboardInterrupt: 

In [16]:
from SensatUrban.helper_ply import read_ply
d = read_ply(path1)
print(np.unique(d['class']))

[ 0  1  2  3  5  7  8  9 10]


In [8]:
path1 = "/home/pavel/ITMO/NIR2/data/SensetUrban_converted/train/cambridge_block_19.ply"
path2 = "/home/pavel/ITMO/NIR2/data/mend_line5_full.ply"

In [5]:
import open3d as o3d
import numpy as np

# Загружаем point cloud
pcd = o3d.io.read_point_cloud(path1)

# Число точек
points = np.asarray(pcd.points)
print("Количество точек:", points.shape[0])
print(pcd.has_colors())
print(pcd)
# Визуализация
# o3d.visualization.draw_geometries([pcd])

Количество точек: 12090250
True
PointCloud with 12090250 points.


In [ ]:
 

def read_ply_data(path, with_rgb=True, with_label=True):
    data = read_ply(path)
    xyz = np.vstack((data['x'], data['y'], data['z'])).T
    if with_rgb and with_label:
        rgb = np.vstack((data['red'], data['green'], data['blue'])).T
        labels = data['class']
        return xyz.astype(np.float32), rgb.astype(np.uint8), labels.astype(np.uint8)
    elif with_rgb and not with_label:
        rgb = np.vstack((data['red'], data['green'], data['blue'])).T
        return xyz.astype(np.float32), rgb.astype(np.uint8)
    elif not with_rgb and with_label:
        labels = data['class']
        return xyz.astype(np.float32), labels.astype(np.uint8)
    elif not with_rgb and not with_label:
        return xyz.astype(np.float32)

NameError: name '__file__' is not defined

In [12]:
import os
import numpy as np
import torch
from torch.utils.data import Dataset
from pyntcloud import PyntCloud
xyz, rgb, labesl = load_ply(path)

KeyError: 'label'